CREATE TABLE IF NOT EXISTS CUSTOMERS(ID INT,NAME STRING,AGE INT,CITY STRING,SALARY FLOAT)
COMMENT 'THIS IS THE CUSTOMER TABLE'
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
STORED AS TEXTFILE 
