CREATE TABLE POKEMON2(ID INT,NAME STRING,TYPE1 STRING,TYPE2 STRING, TOTAL INT,HP INT,ATTACK INT,DEFENCE INT,SP_ATK INT,SP_DEF INT,SPEED INT) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n' tblproperties("skip.header.line.count"="1");

LOAD DATA INPATH '/input_files/Pokemon.csv' INTO TABLE POKEMON2;

select * from POKEMON2;
